config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "fukyos#index"

  resources :fukyos do
    resources :comments, only: :create
    resources :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :users, only: :show do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :fukyo

  validates :c_text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :fukyo
end

app/models/fukyo.rb
class Fukyo < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title,  presence: true
  validates :f_text, presence: true
  validates :image,  presence: true

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search != ""
      Fukyo.where('title LIKE(?)', "%#{search}%")
    else
      Fukyo.all
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many  :fukyos
  has_many  :comments
  has_many  :favorites
  has_many  :relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many  :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many  :followings, through: :relationships, source: :followed
  has_many  :followers, through: :reverse_of_relationships, source: :follower

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  validates :fukyo_sya, presence: true
  validates :profile,   presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fukyo_sya, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/fukyos/#{comment.fukyo.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:c_text).merge(user_id: current_user.id, fukyo_id: params[:fukyo_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @fukyo_favorite = Favorite.new(user_id: current_user.id, fukyo_id: params[:fukyo_id])
    @fukyo_favorite.save
    redirect_to fukyo_path(params[:fukyo_id]) 
  end

  def destroy
    @fukyo_favorite = Favorite.find_by(user_id: current_user.id, fukyo_id: params[:fukyo_id])
    @fukyo_favorite.destroy
    redirect_to fukyo_path(params[:fukyo_id]) 
  end
end

app/controllers/fukyos_controller.rb
class FukyosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_fukyo, only: [:show, :edit, :update]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @fukyos = Fukyo.includes(:user).order("created_at DESC")
  end
  
  def new
  @fukyo = Fukyo.new
  end

  def create
    @fukyo = Fukyo.new(fukyo_params)
    if @fukyo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @fukyo.comments.includes(:user)
    @user = @fukyo.user
    @favorite_count = Favorite.where(fukyo_id: @fukyo.id).count
  end

  def edit
  end

  def update
    if @fukyo.update(fukyo_params)
      redirect_to fukyo_path(@fukyo.id)
    else
      render :edit
    end
  end

  def destroy
    fukyo = Fukyo.find(params[:id])
    fukyo.destroy
    redirect_to root_path
  end

  def search
    @fukyos = Fukyo.search(params[:keyword])
  end

  private
  
  def fukyo_params
    params.require(:fukyo).permit(:title, :f_text, :f_url, :image).merge(user_id: current_user.id)
  end

  def set_fukyo
    @fukyo = Fukyo.find(params[:id])
  end

  def move_to_index 
    @fukyo = Fukyo.find(params[:id])
    unless current_user == @fukyo.user
      redirect_to root_path
    end
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @fukyo_sya = @user.fukyo_sya
    @fukyos = @user.fukyos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/fukyos_helper.rb
module FukyosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fukyos/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集</h3>
    <%= form_with(model: @fukyo, local: true) do |f| %>
      <%= f.text_field :title, placeholder: "お題をどうぞ（必須）" %>
      <%= f.file_field :image %>
      <%= f.text_area :f_text, placeholder: "本文はこちら（必須）", rows: "10" %>
      <%= f.text_field :f_url, placeholder: "お題に関するURL（任意）" %>
      <%= f.submit "変更を保存する" %>
    <% end %>
  </div>
</div>

app/views/fukyos/index.html.erb
<%= form_with(url: search_fukyos_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="contents row">
  <% @fukyos.each do |fukyo| %>
    <%= link_to fukyo_path(fukyo.id) do %>
      <%= image_tag fukyo.image.variant(resize: '500x500'), class: :image_tag %>
    <% end %>
      <span class="name">
      <p><strong class="fukyo-sya"><%= link_to fukyo.user.fukyo_sya, "/users/#{fukyo.user[:id]}" %></strong></p>
      <h1><%= fukyo.title %></h1>
      </span>
  <% end %>
</div>

app/views/fukyos/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>-FUKYO-</h3>
    <%= form_with(model: @fukyo, local: true) do |f| %>
      <%= f.text_field :title, placeholder: "お題をどうぞ（必須）" %>
      <%= f.file_field :image %>
      <%= f.text_area :f_text, placeholder: "本文はこちら（必須）", rows: "10" %>
      <%= f.text_field :f_url, placeholder: "お題に関するURL（任意）" %>
      <%= f.submit "FUKYOする" %>
    <% end %>
  </div>
</div>

app/views/fukyos/search.html.erb
<%= form_with(url: search_fukyos_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="contents row">
  <% @fukyos.each do |fukyo| %>
    <%= link_to fukyo_path(fukyo.id) do %>
      <%= image_tag fukyo.image.variant(resize: '800x800'), class: :image_tag %>
    <% end %>
      <span class="name">
      <p><strong class="fukyo-sya"><%= link_to fukyo.user.fukyo_sya, "/users/#{fukyo.user[:id]}" %></strong></p>
      <h1><%= fukyo.title %></h1>
      </span>
  <% end %>
</div>

app/views/fukyos/show.html.erb
<div class="contents row">
  <%= image_tag @fukyo.image.variant(resize: '800x800'), class: :image_tag %>
    
    <div class="more">
    <% if user_signed_in? %>
      <% if @fukyo.favorited?(current_user) %>
        <%= link_to fukyo_favorite_path(@fukyo.id), method: :delete do %>
        <span style="color:red;">❤︎</span>
        <% end %>
      <% else %>
        <%= link_to fukyo_favorites_path(@fukyo.id), method: :post do %>
        <span>❤</span>
        <% end %>
      <% end %>
      <%= @favorite_count %>

      <% if current_user.id == @fukyo.user_id %>
      <ul class="more_list">
        <li class="edit-botn">
          <%= link_to '編 集', edit_fukyo_path(@fukyo.id), method: :get %>
        </li>
        <li class="edit-botn">
          <%= link_to '削 除', fukyo_path(@fukyo.id), method: :delete %>
        </li>
      </ul>
      <% end %>
    </div>
    <% else %>
      <span>❤<%= @favorite_count %></span>
    <% end %>

    <p><strong class="fukyo-sya"><%= link_to @fukyo.user.fukyo_sya, "/users/#{@fukyo.user_id}" %> </strong></p>

    <h1><%= @fukyo.title %></h1>
    <span class="name"><%= @fukyo.f_text %></span>
    <div><%= @fukyo.f_url%></div>

    <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@fukyo, @comment], local: true) do |f| %>
        <%= f.text_area :c_text, placeholder: "節度を守って、コメントしてみよう！", rows: "2" %>
        <%= f.submit "コメントする" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>- コメント一覧 -</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.fukyo_sya, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.c_text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FUKYO app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">FUKYO app</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.fukyo_sya %>
              <ul class="user__info">
                <li>
                  <%= link_to "マイページ", "/users/#{current_user.id}" %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </span>
            <%= link_to "FUKYO", new_fukyo_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
        <footer>
      <p>
        Copyright FUKYOapp 2022.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<%= form_with(url: search_fukyos_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>

<div class="contents row">
  <h1 class="user-title">-<%= @fukyo_sya %>さんのFUKYO-</h1>
  <p><%= @user.profile %></p>

  <h1>フォロー: <%= @user.followings.count %>
  　フォロワー: <%= @user.followers.count %>
  
    <span class="follow-botton">
      <% if current_user.following?(@user) %>
        <%= link_to "フォロー解除", user_relationship_path(@user.id), method: :delete %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
      <% end %>
    </span>
  </h2>

  <% @fukyos.each do |fukyo| %>
    <%= link_to fukyo_path(fukyo.id) do %>
      <%= image_tag fukyo.image.variant(resize: '500x500'), class: :image_tag %>
    <% end %>

      <h1 class="fukyo-title"><%= fukyo.title %></h1>
      <span class="name">
        <div><%= fukyo.f_text %></div>
      </span>
  <% end %>
</div>